apiVersion: v1
kind: Service
metadata:
  name: personal-website
  labels:
    run: personal-website
    kind: frontend
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: personal-website
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: personal-website
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: personal-website
    spec:
      containers:
      - name: personal-website
        image: trisgerra92/personal-website
        ports:
        - containerPort: 8080
        - containerPort: 443   